# Generated by Django 6.0.3 on 2026-04-20 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_senha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemlink',
            name='capsula',
        ),
        migrations.DeleteModel(
            name='ItemImagem',
        ),
        migrations.DeleteModel(
            name='ItemLink',
        ),
    ]
