# Generated by Django 6.0.3 on 2026-04-20 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_itemlink_capsula_delete_itemimagem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capsula',
            name='finalizada',
        ),
    ]
