# Generated by Django 6.0.3 on 2026-04-21 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_capsula_finalizada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capsula',
            name='criada_em',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='capsula',
            name='data_abertura',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='itemtexto',
            name='criado_em',
            field=models.DateField(auto_now_add=True),
        ),
    ]
